name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Install and Build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout from git'
        uses: actions/checkout@v2
      - name: 'Setup Node.js environment'
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '15.x'
      - name: Install Dependencies
        run: npm ci --force
      - name: Build
        run: npm run build
