name: CD

on:
  push:
    branches: [master]
    workflow_dispatch:

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout from git'
        uses: actions/checkout@v2
      - name: 'Setup Node.js environment'
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '15.x'
      - name: Install Dependencies
        run: npm ci --force
      - name: Build and deploy
        run: npm run deploy
