name: main

on:
  push:
  workflow_dispatch:

jobs:
  install:
    name: Install project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from git
        uses: actions/checkout@v2
      - name: 'Setup Node.js environment'
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '15.x'
      - name: Install Dependencies
        run: npm ci --force
      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout from git
        uses: actions/checkout@v2
      - name: 'Setup Node.js environment'
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '15.x'
      - name: Install Dependencies
        run: npm ci --force
      - name: Run Tests
        run: npm run test:coverage
        env:
          CI: true
      - name: Upload CodeCoverage
        uses: codecov/codecov-action@master
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: client/coverage/*.json
          flags: unittests

  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout from git'
        uses: actions/checkout@v2
      - name: 'Setup Node.js environment'
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '15.x'
      - name: Install Dependencies
        run: npm ci --force
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: ${{ github.ref == 'ref/heads/master'}}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
